### ISSUE TITLE
Vocabolari Controllati: pubblicare i vocabolari in formato jsonschema

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#162]
## Mi aspetto

Che i vocabolari possano essere pubblicati sperimentalmente in formato json-schema 
con la sintassi:

```
NomeVocabolario:
  oneOf:
  - const: <skos:identifier>
    title: <skos:prefLabel@it>
  - ...
```
